layers:
  - type: conv1d
    options:
      filters: 8
      kernelSize: 24
  - type: conv1d
    options:
      filters: 8
      kernelSize: 24
  - type: flatten
  - type: dense
    options:
      units: 288
      activation: relu
  - type: dense
    options:
      units: 288
fitOptions:
  epochs: 50
  validationSplit: 0.25
compileOptions:
  optimizer: adam
  loss: meanSquaredError
duration: P4W
inputSize: 192
outputSize: 96
