layers:
  - type: conv1d
    options:
      inputShape:
        - 192
        - 2
      filters: 24
      kernelSize: 24
  - type: maxPooling1d
    options:
      poolSize: 8
      units: 96
  - type: conv1d
    options:
      filters: 24
      kernelSize: 12
  - type: dense
    options:
      units: 96
      activation: relu
  - type: flatten
  - type: dense
    options:
      units: 96
      activation: relu
  - type: dense
    options:
      units: 96
fitOptions:
  epochs: 50
  validationSplit: 0.25
compileOptions:
  optimizer: adam
  loss: meanSquaredError
duration: P4W
