root: true
extends:
  - typescript
  - typescript/react
  - typescript/prettier
  - typescript/prettier-react
plugins:
  - prettier
rules:
  require-jsdoc: off
  prettier/prettier:
      - error
      - singleQuote: true
        trailingComma: all
settings:
  react:
    version: "16.12.0"
