recognitions:
  - name: name
    type: text
    x: -0.47
    'y': -0.505
    width: 0.54
    height: 0.09
  - name: lottery
    type: number
    x: 0.1
    'y': -0.5
    width: 0.13
    height: 0.07
  - name: price
    type: number
    x: -0.195
    'y': -0.405
    width: 0.39
    height: 0.08
triggers:
  - x: 0.3
    'y': -0.36
    color:
      - 255
      - 255
      - 255
  - x: 0.2
    'y': -0.36
    color:
      - 219
      - 241
      - 255
fps: 10
