recognitions:
  - name: name
    type: text
    x: -0.405
    'y': -0.49
    width: 0.52
    height: 0.09
  - name: lottery
    type: number
    x: 0.15
    'y': -0.475
    width: 0.13
    height: 0.06
  - name: price
    type: number
    x: -0.135
    'y': -0.39
    width: 0.39
    height: 0.08
triggers:
  - x: 0.26
    'y': -0.33
    color:
      - 219
      - 241
      - 255
fps: 10
