$schema: http://json-schema.org/draft-07/schema#
title: ModelConfiguration
type: object
properties:
  layers:
    type: array
    items:
      type: object
  fitOptions:
    type: object
    properties:
      epochs:
        type: number
      validationSplit:
        type: number
  compileOptions:
    type: object
    properties:
      optimizer:
        type: string
      loss:
        type: string
    required:
      - optimizer
      - loss
  timeUnit:
    $ref: "#/definitions/Duration"
  timeDomain:
    min:
      $ref: "#/definitions/Duration"
    max:
      $ref: "#/definitions/Duration"
  inputDuration:
    $ref: "#/definitions/Duration"
  outputDuration:
    $ref: "#/definitions/Duration"
  benefitDuration:
    $ref: "#/definitions/Duration"
required:
  - layers
  - compileOptions
  - timeUnit
  - timeDomain
  - inputDuration
  - outputDuration
  - benefitDuration
definitions:
  Duration:
    type: string
    pattern: "^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"
