name: Build and Deploy

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp gs://mercurius-6026e.appspot.com/group1.bin packages/browser/assets/group1.bin
      - run: npm ci
      - run: npm run lint
      - run: npm run build-production
      - run: npx firebase deploy
        if: github.ref == 'refs/heads/master'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
