name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap packages
        run: npx lerna bootstrap
        working-directory: functions
      - name: Build
        run: npm run build:production
      - name: Deploy to Firebase
        run: npx firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
